POST http://localhost:5000/registeruser
Content-Type: application/json

{
     "id": "p1",
     "name": "Bob",
     "gender": "M",
     "email": "tulidey06@gmail.com",
     "password": "tulidey",
     "phn": "01886874652",
     "usertype": "patient",
     "org": "Org1MSP"
}
