POST http://localhost:5000/registeruser
Content-Type: application/json

{
     "id": "doc1",
     "name": "Albert",
     "gender": "M",
     "email": "tulidey06@gmail.com",
     "password": "hdg354",
     "phn": "02156874652",
     "usertype": "doctor",
     "org": "Org1MSP"
}
