POST http://localhost:5000/verifysig
Content-Type: application/json

{
     "txid": "8b540def661748517df0dc0087193fa4b628c5860696f0bca599c723fbd8d64d",
     "pubkey": "-----BEGIN CERTIFICATE-----\nMIICfjCCAiSgAwIBAgIUBoiINqafkg/DKJyTbMV/DVvC+LcwCgYIKoZIzj0EAwIw\ncDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH\nEwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh\nLm9yZzEuZXhhbXBsZS5jb20wHhcNMjMwNDEzMTQ0NzAwWhcNMjQwNDEyMTcwNjAw\nWjBBMTAwCwYDVQQLEwRvcmcxMA0GA1UECxMGY2xpZW50MBIGA1UECxMLZGVwYXJ0\nbWVudDExDTALBgNVBAMTBGRvYzEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAASp\nc/RWHewhwiBhoegMkd21VKcsp5oNR1shGg4X6nCau/wA6xbz88h1oBfmqxEjVsDp\nTdWpOPhpjMFY39/hyjWUo4HKMIHHMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8E\nAjAAMB0GA1UdDgQWBBR2L3M8WRmwGXqRcnSyWMkj8KqjRjAfBgNVHSMEGDAWgBSJ\nDwwdjOZiJqSPjy38ghd1Uu8vMjBnBggqAwQFBgcIAQRbeyJhdHRycyI6eyJoZi5B\nZmZpbGlhdGlvbiI6Im9yZzEuZGVwYXJ0bWVudDEiLCJoZi5FbnJvbGxtZW50SUQi\nOiJkb2MxIiwiaGYuVHlwZSI6ImNsaWVudCJ9fTAKBggqhkjOPQQDAgNIADBFAiEA\n0N1T8AY+S6LHymm/uByBns9QaIK+3x6TDziFAX114YQCIAnfslpqhCClAbfGvpTU\nAJuR5KrZ9YSKfndWZanE69xs\n-----END CERTIFICATE-----"
}