POST http://localhost:5000/CreatePrescription
Content-Type: application/json

{
     "id": "pres1",
     "pid": "p1",
     "name": "Bob",
     "age": "22",
     "date": "21/10/22",
     "disease": "Pneumonia",
     "medicine": "amoxicillin tablet"
}

