POST http://localhost:5000/registerpatient
Content-Type: application/json

{
     "id": "p1",
     "name": "Alice",
     "gender": "F",
     "email": "alice@gmail.com",
     "phn": "02156874652"
}



